### PR TITLE
Move BCC down to libraries section

### PR DESCRIPTION
**Pull request by anakryiko**
Move BCC project to the bottom of libraries section.

Signed-off-by: Andrii Nakryiko <andrii@kernel.org>

### CODE REVIEW

**Review by lmb — APPROVED** [review]

**Comment by dthaler** [comment]
It looks odd to me that the visual style of the bcc entry is different from the style of the other libraries.  Any ideas?

**Comment by anakryiko** [comment]
TBH, BCC as a programming framework is considered to be a legacy way of doing things and is not recommended for new applications. It is still a great collection of performance monitoring tooling, so I don't know where and how we should keep it, but it might not be in Libraries section. Don't know.

**Comment by borkmann** [comment]
> TBH, BCC as a programming framework is considered to be a legacy way of doing things and is not recommended for new applications. It is still a great collection of performance monitoring tooling, so I don't know where and how we should keep it, but it might not be in Libraries section. Don't know.

Should we just keep it as-is then? I presume vast majority of people are users of the tool collection?

**Comment by dthaler** [comment]
I think Andrii makes a good point, suggest we just keep as is then.

**Comment by anakryiko** [comment]
Abandoning this then.

**Pull request closed without merging**
